// CONTACTS actions
export const LOAD_CONTACTS = 'LOAD_CONTACTS'
export const LOAD_CONTACTS_REQUEST = 'LOAD_CONTACTS_REQUEST'
export const LOAD_CONTACTS_FAILURE = 'LOAD_CONTACTS_FAILURE'
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS'
export const WEB_SOCKET_CREATED_SUCCESS = 'WEB_SOCKET_CREATED_SUCCESS'
export const UPDATE_CONTACT_STATUS = 'UPDATE_CONTACT_STATUS'
export const SYNC_CONTACTS = 'SYNC_CONTACTS'
export const SELECT_CONTACT = 'SELECT_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

// SMSBuilder actions

export const UPDATE_MESSAGE_BODY = 'UPDATE_MESSAGE_BODY'
export const UPDATE_MEDIA_URL = 'UPDATE_MEDIA_URL'
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'
